### PR TITLE
Rebuild action, implemented by destorying disks and profile and then …

### PR DESCRIPTION
**Pull request by preluigi**
…recreate them

### CODE REVIEW

**Comment by displague** [comment]
Thanks for the PR!

**Comment by displague** [comment]
That create blob that was copied is the [biggest refactor target](https://codeclimate.com/github/displague/vagrant-linode/VagrantPlugins::Linode::Actions::Create).  Copying it doubles the mess.

Could you consolidate the duplication in some way?

**Comment by preluigi** [comment]
can consider that in my spare time; I'll let you know.

**Comment by preluigi** [comment]
I can consider that in my spare time; I'll let you know.

Luigi

**Pull request merged**
